env:
  global:
    - secure: L7CXe36PJw0l4PxEGK0erpHxi4fHXf43S9tUOLH7HblbJn+Jl6WhUFlFHizMQ2cvHLj1djv3gRem0FhL2hzLMN88pmpziXDBcPQXvBg1f/EAs0AZrBH62hqile9zvyebK3dY4O1SsHR6DK54VSGBByQYbQIbADL7vEmG1mwP9fc=
    - secure: AxnDnt9Sr7CwzHbFEB20GJm5GTweCGlyIhaN9dmHqUJs//UmskqLDkIczCLpgmV2vFbh2YXw6Nwy8YQThz6HhZTOLL0U5SQsyan1vSKTuOMzz949SPIghes7sOeP4sE7vN5vm51PFjMBsNF5fDyPV+K5wIyGH7u4rMVTbv4R0Ds=

language: node_js
node_js:
  - "4.1"
env:
  - CXX=g++-4.8

sudo: false